# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_control.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_dialog_control_edit(object):
    def setupUi(self, dialog_control_edit):
        dialog_control_edit.setObjectName(_fromUtf8("dialog_control_edit"))
        dialog_control_edit.resize(808, 520)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(dialog_control_edit.sizePolicy().hasHeightForWidth())
        dialog_control_edit.setSizePolicy(sizePolicy)
        self.gridLayout_6 = QtGui.QGridLayout(dialog_control_edit)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.frame = QtGui.QFrame(dialog_control_edit)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_5 = QtGui.QGridLayout(self.frame)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.frame_kp = QtGui.QFrame(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_kp.sizePolicy().hasHeightForWidth())
        self.frame_kp.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.frame_kp.setPalette(palette)
        self.frame_kp.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_kp.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_kp.setObjectName(_fromUtf8("frame_kp"))
        self.formLayout = QtGui.QFormLayout(self.frame_kp)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.ctrl_main_use = QtGui.QCheckBox(self.frame_kp)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ctrl_main_use.sizePolicy().hasHeightForWidth())
        self.ctrl_main_use.setSizePolicy(sizePolicy)
        self.ctrl_main_use.setObjectName(_fromUtf8("ctrl_main_use"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.SpanningRole, self.ctrl_main_use)
        self.label_kp = QtGui.QLabel(self.frame_kp)
        self.label_kp.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_kp.setObjectName(_fromUtf8("label_kp"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_kp)
        self.edit_kp = QtGui.QDoubleSpinBox(self.frame_kp)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_kp.sizePolicy().hasHeightForWidth())
        self.edit_kp.setSizePolicy(sizePolicy)
        self.edit_kp.setDecimals(3)
        self.edit_kp.setMinimum(-9999.0)
        self.edit_kp.setMaximum(9999.99)
        self.edit_kp.setObjectName(_fromUtf8("edit_kp"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.edit_kp)
        self.gridLayout_5.addWidget(self.frame_kp, 2, 0, 1, 1)
        self.label_ID = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_ID.sizePolicy().hasHeightForWidth())
        self.label_ID.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_ID.setFont(font)
        self.label_ID.setTextFormat(QtCore.Qt.PlainText)
        self.label_ID.setObjectName(_fromUtf8("label_ID"))
        self.gridLayout_5.addWidget(self.label_ID, 1, 0, 1, 1)
        self.frame_pre_filter = QtGui.QFrame(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_pre_filter.sizePolicy().hasHeightForWidth())
        self.frame_pre_filter.setSizePolicy(sizePolicy)
        self.frame_pre_filter.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_pre_filter.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_pre_filter.setObjectName(_fromUtf8("frame_pre_filter"))
        self.gridLayout = QtGui.QGridLayout(self.frame_pre_filter)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.checkBox_pre_use = QtGui.QCheckBox(self.frame_pre_filter)
        self.checkBox_pre_use.setObjectName(_fromUtf8("checkBox_pre_use"))
        self.gridLayout.addWidget(self.checkBox_pre_use, 0, 0, 1, 2)
        self.label_pre_tau_zero = QtGui.QLabel(self.frame_pre_filter)
        self.label_pre_tau_zero.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_pre_tau_zero.setObjectName(_fromUtf8("label_pre_tau_zero"))
        self.gridLayout.addWidget(self.label_pre_tau_zero, 1, 0, 1, 1)
        self.edit_pre_tau_zero = QtGui.QDoubleSpinBox(self.frame_pre_filter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_pre_tau_zero.sizePolicy().hasHeightForWidth())
        self.edit_pre_tau_zero.setSizePolicy(sizePolicy)
        self.edit_pre_tau_zero.setDecimals(3)
        self.edit_pre_tau_zero.setProperty("value", 1.0)
        self.edit_pre_tau_zero.setObjectName(_fromUtf8("edit_pre_tau_zero"))
        self.gridLayout.addWidget(self.edit_pre_tau_zero, 1, 1, 1, 1)
        self.label_pre_tau_pole = QtGui.QLabel(self.frame_pre_filter)
        self.label_pre_tau_pole.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_pre_tau_pole.setObjectName(_fromUtf8("label_pre_tau_pole"))
        self.gridLayout.addWidget(self.label_pre_tau_pole, 2, 0, 1, 1)
        self.edit_pre_tau_pole = QtGui.QDoubleSpinBox(self.frame_pre_filter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_pre_tau_pole.sizePolicy().hasHeightForWidth())
        self.edit_pre_tau_pole.setSizePolicy(sizePolicy)
        self.edit_pre_tau_pole.setDecimals(3)
        self.edit_pre_tau_pole.setProperty("value", 1.0)
        self.edit_pre_tau_pole.setObjectName(_fromUtf8("edit_pre_tau_pole"))
        self.gridLayout.addWidget(self.edit_pre_tau_pole, 2, 1, 1, 1)
        self.gridLayout_5.addWidget(self.frame_pre_filter, 3, 0, 1, 1)
        self.label_ID_lead = QtGui.QLabel(self.frame)
        self.label_ID_lead.setObjectName(_fromUtf8("label_ID_lead"))
        self.gridLayout_5.addWidget(self.label_ID_lead, 0, 0, 1, 1)
        self.frame_out_limit = QtGui.QFrame(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_out_limit.sizePolicy().hasHeightForWidth())
        self.frame_out_limit.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.frame_out_limit.setPalette(palette)
        self.frame_out_limit.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_out_limit.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_out_limit.setObjectName(_fromUtf8("frame_out_limit"))
        self.formLayout_3 = QtGui.QFormLayout(self.frame_out_limit)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.checkBox_out_limit = QtGui.QCheckBox(self.frame_out_limit)
        self.checkBox_out_limit.setObjectName(_fromUtf8("checkBox_out_limit"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.SpanningRole, self.checkBox_out_limit)
        self.label_out_limit = QtGui.QLabel(self.frame_out_limit)
        self.label_out_limit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_out_limit.setObjectName(_fromUtf8("label_out_limit"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_out_limit)
        self.edit_output_limit = QtGui.QDoubleSpinBox(self.frame_out_limit)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_output_limit.sizePolicy().hasHeightForWidth())
        self.edit_output_limit.setSizePolicy(sizePolicy)
        self.edit_output_limit.setMaximum(9999.99)
        self.edit_output_limit.setObjectName(_fromUtf8("edit_output_limit"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.edit_output_limit)
        self.gridLayout_5.addWidget(self.frame_out_limit, 2, 3, 1, 1)
        self.frame_kp_integrator_5 = QtGui.QFrame(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_kp_integrator_5.sizePolicy().hasHeightForWidth())
        self.frame_kp_integrator_5.setSizePolicy(sizePolicy)
        self.frame_kp_integrator_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_kp_integrator_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_kp_integrator_5.setObjectName(_fromUtf8("frame_kp_integrator_5"))
        self.gridLayout_4 = QtGui.QGridLayout(self.frame_kp_integrator_5)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.checkBox_ff_use = QtGui.QCheckBox(self.frame_kp_integrator_5)
        self.checkBox_ff_use.setObjectName(_fromUtf8("checkBox_ff_use"))
        self.gridLayout_4.addWidget(self.checkBox_ff_use, 0, 0, 1, 2)
        self.frame_ff_pole_zero = QtGui.QFrame(self.frame_kp_integrator_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_ff_pole_zero.sizePolicy().hasHeightForWidth())
        self.frame_ff_pole_zero.setSizePolicy(sizePolicy)
        self.frame_ff_pole_zero.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_ff_pole_zero.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_ff_pole_zero.setObjectName(_fromUtf8("frame_ff_pole_zero"))
        self.formLayout_5 = QtGui.QFormLayout(self.frame_ff_pole_zero)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.checkBox_ff_pole_zero = QtGui.QCheckBox(self.frame_ff_pole_zero)
        self.checkBox_ff_pole_zero.setObjectName(_fromUtf8("checkBox_ff_pole_zero"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.SpanningRole, self.checkBox_ff_pole_zero)
        self.label_ff_tau_zero = QtGui.QLabel(self.frame_ff_pole_zero)
        self.label_ff_tau_zero.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_ff_tau_zero.setObjectName(_fromUtf8("label_ff_tau_zero"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_ff_tau_zero)
        self.edit_ff_tau_zero = QtGui.QDoubleSpinBox(self.frame_ff_pole_zero)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_ff_tau_zero.sizePolicy().hasHeightForWidth())
        self.edit_ff_tau_zero.setSizePolicy(sizePolicy)
        self.edit_ff_tau_zero.setDecimals(3)
        self.edit_ff_tau_zero.setProperty("value", 1.0)
        self.edit_ff_tau_zero.setObjectName(_fromUtf8("edit_ff_tau_zero"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.edit_ff_tau_zero)
        self.label_ff_tau_pole = QtGui.QLabel(self.frame_ff_pole_zero)
        self.label_ff_tau_pole.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_ff_tau_pole.setObjectName(_fromUtf8("label_ff_tau_pole"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_ff_tau_pole)
        self.edit_ff_tau_pole = QtGui.QDoubleSpinBox(self.frame_ff_pole_zero)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_ff_tau_pole.sizePolicy().hasHeightForWidth())
        self.edit_ff_tau_pole.setSizePolicy(sizePolicy)
        self.edit_ff_tau_pole.setDecimals(3)
        self.edit_ff_tau_pole.setProperty("value", 1.0)
        self.edit_ff_tau_pole.setObjectName(_fromUtf8("edit_ff_tau_pole"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.FieldRole, self.edit_ff_tau_pole)
        self.gridLayout_4.addWidget(self.frame_ff_pole_zero, 0, 2, 3, 1)
        self.label_ff_kp = QtGui.QLabel(self.frame_kp_integrator_5)
        self.label_ff_kp.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_ff_kp.setObjectName(_fromUtf8("label_ff_kp"))
        self.gridLayout_4.addWidget(self.label_ff_kp, 1, 0, 1, 1)
        self.edit_ff_kp = QtGui.QDoubleSpinBox(self.frame_kp_integrator_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_ff_kp.sizePolicy().hasHeightForWidth())
        self.edit_ff_kp.setSizePolicy(sizePolicy)
        self.edit_ff_kp.setDecimals(3)
        self.edit_ff_kp.setMinimum(-9999.0)
        self.edit_ff_kp.setMaximum(9999.99)
        self.edit_ff_kp.setObjectName(_fromUtf8("edit_ff_kp"))
        self.gridLayout_4.addWidget(self.edit_ff_kp, 1, 1, 1, 1)
        self.gridLayout_5.addWidget(self.frame_kp_integrator_5, 4, 0, 1, 2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem, 5, 1, 1, 1)
        self.frame_pole_zero_back = QtGui.QFrame(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_pole_zero_back.sizePolicy().hasHeightForWidth())
        self.frame_pole_zero_back.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.frame_pole_zero_back.setPalette(palette)
        self.frame_pole_zero_back.setStyleSheet(_fromUtf8("border-color: rgb(170, 255, 127);\n"
""))
        self.frame_pole_zero_back.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_pole_zero_back.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_pole_zero_back.setLineWidth(2)
        self.frame_pole_zero_back.setMidLineWidth(2)
        self.frame_pole_zero_back.setObjectName(_fromUtf8("frame_pole_zero_back"))
        self.gridLayout_3 = QtGui.QGridLayout(self.frame_pole_zero_back)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.checkBox_lead_back = QtGui.QCheckBox(self.frame_pole_zero_back)
        self.checkBox_lead_back.setObjectName(_fromUtf8("checkBox_lead_back"))
        self.gridLayout_3.addWidget(self.checkBox_lead_back, 0, 0, 1, 2)
        self.label_tau_zero_back = QtGui.QLabel(self.frame_pole_zero_back)
        self.label_tau_zero_back.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_tau_zero_back.setObjectName(_fromUtf8("label_tau_zero_back"))
        self.gridLayout_3.addWidget(self.label_tau_zero_back, 1, 0, 1, 1)
        self.edit_tau_zero_back = QtGui.QDoubleSpinBox(self.frame_pole_zero_back)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_tau_zero_back.sizePolicy().hasHeightForWidth())
        self.edit_tau_zero_back.setSizePolicy(sizePolicy)
        self.edit_tau_zero_back.setDecimals(3)
        self.edit_tau_zero_back.setProperty("value", 1.0)
        self.edit_tau_zero_back.setObjectName(_fromUtf8("edit_tau_zero_back"))
        self.gridLayout_3.addWidget(self.edit_tau_zero_back, 1, 1, 1, 1)
        self.label_tau_pole_back = QtGui.QLabel(self.frame_pole_zero_back)
        self.label_tau_pole_back.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_tau_pole_back.setObjectName(_fromUtf8("label_tau_pole_back"))
        self.gridLayout_3.addWidget(self.label_tau_pole_back, 2, 0, 1, 1)
        self.edit_tau_pole_back = QtGui.QDoubleSpinBox(self.frame_pole_zero_back)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_tau_pole_back.sizePolicy().hasHeightForWidth())
        self.edit_tau_pole_back.setSizePolicy(sizePolicy)
        self.edit_tau_pole_back.setDecimals(3)
        self.edit_tau_pole_back.setProperty("value", 1.0)
        self.edit_tau_pole_back.setObjectName(_fromUtf8("edit_tau_pole_back"))
        self.gridLayout_3.addWidget(self.edit_tau_pole_back, 2, 1, 1, 1)
        self.gridLayout_5.addWidget(self.frame_pole_zero_back, 3, 1, 1, 1)
        self.frame_post_integrator = QtGui.QFrame(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_post_integrator.sizePolicy().hasHeightForWidth())
        self.frame_post_integrator.setSizePolicy(sizePolicy)
        self.frame_post_integrator.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_post_integrator.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_post_integrator.setObjectName(_fromUtf8("frame_post_integrator"))
        self.gridLayout_7 = QtGui.QGridLayout(self.frame_post_integrator)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.checkBox_post_integrator = QtGui.QCheckBox(self.frame_post_integrator)
        self.checkBox_post_integrator.setObjectName(_fromUtf8("checkBox_post_integrator"))
        self.gridLayout_7.addWidget(self.checkBox_post_integrator, 0, 0, 1, 1)
        self.checkBox_post_integrator_zero = QtGui.QCheckBox(self.frame_post_integrator)
        self.checkBox_post_integrator_zero.setObjectName(_fromUtf8("checkBox_post_integrator_zero"))
        self.gridLayout_7.addWidget(self.checkBox_post_integrator_zero, 0, 1, 1, 1)
        self.label_post_tau_i = QtGui.QLabel(self.frame_post_integrator)
        self.label_post_tau_i.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_post_tau_i.setObjectName(_fromUtf8("label_post_tau_i"))
        self.gridLayout_7.addWidget(self.label_post_tau_i, 1, 0, 1, 1)
        self.edit_post_tau_i = QtGui.QDoubleSpinBox(self.frame_post_integrator)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_post_tau_i.sizePolicy().hasHeightForWidth())
        self.edit_post_tau_i.setSizePolicy(sizePolicy)
        self.edit_post_tau_i.setDecimals(3)
        self.edit_post_tau_i.setProperty("value", 1.0)
        self.edit_post_tau_i.setObjectName(_fromUtf8("edit_post_tau_i"))
        self.gridLayout_7.addWidget(self.edit_post_tau_i, 1, 1, 1, 1)
        self.label_post_limit = QtGui.QLabel(self.frame_post_integrator)
        self.label_post_limit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_post_limit.setObjectName(_fromUtf8("label_post_limit"))
        self.gridLayout_7.addWidget(self.label_post_limit, 2, 0, 1, 1)
        self.edit_post_integrator_limit = QtGui.QDoubleSpinBox(self.frame_post_integrator)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_post_integrator_limit.sizePolicy().hasHeightForWidth())
        self.edit_post_integrator_limit.setSizePolicy(sizePolicy)
        self.edit_post_integrator_limit.setDecimals(3)
        self.edit_post_integrator_limit.setMaximum(9999.99)
        self.edit_post_integrator_limit.setObjectName(_fromUtf8("edit_post_integrator_limit"))
        self.gridLayout_7.addWidget(self.edit_post_integrator_limit, 2, 1, 1, 1)
        self.gridLayout_5.addWidget(self.frame_post_integrator, 3, 2, 1, 2)
        self.frame_integrator = QtGui.QFrame(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_integrator.sizePolicy().hasHeightForWidth())
        self.frame_integrator.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.frame_integrator.setPalette(palette)
        self.frame_integrator.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_integrator.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_integrator.setObjectName(_fromUtf8("frame_integrator"))
        self.formLayout_2 = QtGui.QFormLayout(self.frame_integrator)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.checkBox_integrator_use = QtGui.QCheckBox(self.frame_integrator)
        self.checkBox_integrator_use.setObjectName(_fromUtf8("checkBox_integrator_use"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.SpanningRole, self.checkBox_integrator_use)
        self.label_tau_i = QtGui.QLabel(self.frame_integrator)
        self.label_tau_i.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_tau_i.setObjectName(_fromUtf8("label_tau_i"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_tau_i)
        self.edit_tau_i = QtGui.QDoubleSpinBox(self.frame_integrator)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_tau_i.sizePolicy().hasHeightForWidth())
        self.edit_tau_i.setSizePolicy(sizePolicy)
        self.edit_tau_i.setDecimals(3)
        self.edit_tau_i.setProperty("value", 1.0)
        self.edit_tau_i.setObjectName(_fromUtf8("edit_tau_i"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.edit_tau_i)
        self.label_integrator_limit = QtGui.QLabel(self.frame_integrator)
        self.label_integrator_limit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_integrator_limit.setObjectName(_fromUtf8("label_integrator_limit"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_integrator_limit)
        self.edit_integrator_limit = QtGui.QDoubleSpinBox(self.frame_integrator)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_integrator_limit.sizePolicy().hasHeightForWidth())
        self.edit_integrator_limit.setSizePolicy(sizePolicy)
        self.edit_integrator_limit.setDecimals(3)
        self.edit_integrator_limit.setMaximum(9999.99)
        self.edit_integrator_limit.setProperty("value", 1.0)
        self.edit_integrator_limit.setObjectName(_fromUtf8("edit_integrator_limit"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.edit_integrator_limit)
        self.gridLayout_5.addWidget(self.frame_integrator, 2, 2, 1, 1)
        self.frame_pole_zero_fwd = QtGui.QFrame(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_pole_zero_fwd.sizePolicy().hasHeightForWidth())
        self.frame_pole_zero_fwd.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.frame_pole_zero_fwd.setPalette(palette)
        self.frame_pole_zero_fwd.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_pole_zero_fwd.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_pole_zero_fwd.setObjectName(_fromUtf8("frame_pole_zero_fwd"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame_pole_zero_fwd)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_tau_pole_fwd = QtGui.QLabel(self.frame_pole_zero_fwd)
        self.label_tau_pole_fwd.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_tau_pole_fwd.setObjectName(_fromUtf8("label_tau_pole_fwd"))
        self.gridLayout_2.addWidget(self.label_tau_pole_fwd, 2, 0, 1, 1)
        self.label_tau_zero_fwd = QtGui.QLabel(self.frame_pole_zero_fwd)
        self.label_tau_zero_fwd.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_tau_zero_fwd.setObjectName(_fromUtf8("label_tau_zero_fwd"))
        self.gridLayout_2.addWidget(self.label_tau_zero_fwd, 1, 0, 1, 1)
        self.edit_tau_pole_fwd = QtGui.QDoubleSpinBox(self.frame_pole_zero_fwd)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_tau_pole_fwd.sizePolicy().hasHeightForWidth())
        self.edit_tau_pole_fwd.setSizePolicy(sizePolicy)
        self.edit_tau_pole_fwd.setDecimals(3)
        self.edit_tau_pole_fwd.setProperty("value", 1.0)
        self.edit_tau_pole_fwd.setObjectName(_fromUtf8("edit_tau_pole_fwd"))
        self.gridLayout_2.addWidget(self.edit_tau_pole_fwd, 2, 1, 1, 1)
        self.edit_tau_zero_fwd = QtGui.QDoubleSpinBox(self.frame_pole_zero_fwd)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_tau_zero_fwd.sizePolicy().hasHeightForWidth())
        self.edit_tau_zero_fwd.setSizePolicy(sizePolicy)
        self.edit_tau_zero_fwd.setDecimals(3)
        self.edit_tau_zero_fwd.setProperty("value", 1.0)
        self.edit_tau_zero_fwd.setObjectName(_fromUtf8("edit_tau_zero_fwd"))
        self.gridLayout_2.addWidget(self.edit_tau_zero_fwd, 1, 1, 1, 1)
        self.checkBox_lead_fwd = QtGui.QCheckBox(self.frame_pole_zero_fwd)
        self.checkBox_lead_fwd.setObjectName(_fromUtf8("checkBox_lead_fwd"))
        self.gridLayout_2.addWidget(self.checkBox_lead_fwd, 0, 0, 1, 2)
        self.gridLayout_5.addWidget(self.frame_pole_zero_fwd, 2, 1, 1, 1)
        self.gridLayout_6.addWidget(self.frame, 0, 0, 1, 3)
        self.pushButton_ctrlRetry = QtGui.QPushButton(dialog_control_edit)
        self.pushButton_ctrlRetry.setObjectName(_fromUtf8("pushButton_ctrlRetry"))
        self.gridLayout_6.addWidget(self.pushButton_ctrlRetry, 1, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(dialog_control_edit)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Help|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_6.addWidget(self.buttonBox, 1, 2, 1, 1)
        self.pushButton_ctrlIniLoad = QtGui.QPushButton(dialog_control_edit)
        self.pushButton_ctrlIniLoad.setObjectName(_fromUtf8("pushButton_ctrlIniLoad"))
        self.gridLayout_6.addWidget(self.pushButton_ctrlIniLoad, 1, 1, 1, 1)

        self.retranslateUi(dialog_control_edit)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), dialog_control_edit.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), dialog_control_edit.reject)
        QtCore.QMetaObject.connectSlotsByName(dialog_control_edit)
        dialog_control_edit.setTabOrder(self.ctrl_main_use, self.edit_kp)
        dialog_control_edit.setTabOrder(self.edit_kp, self.checkBox_integrator_use)
        dialog_control_edit.setTabOrder(self.checkBox_integrator_use, self.edit_tau_i)
        dialog_control_edit.setTabOrder(self.edit_tau_i, self.edit_integrator_limit)
        dialog_control_edit.setTabOrder(self.edit_integrator_limit, self.checkBox_lead_fwd)
        dialog_control_edit.setTabOrder(self.checkBox_lead_fwd, self.edit_tau_zero_fwd)
        dialog_control_edit.setTabOrder(self.edit_tau_zero_fwd, self.edit_tau_pole_fwd)
        dialog_control_edit.setTabOrder(self.edit_tau_pole_fwd, self.checkBox_out_limit)
        dialog_control_edit.setTabOrder(self.checkBox_out_limit, self.edit_output_limit)
        dialog_control_edit.setTabOrder(self.edit_output_limit, self.checkBox_pre_use)
        dialog_control_edit.setTabOrder(self.checkBox_pre_use, self.edit_pre_tau_zero)
        dialog_control_edit.setTabOrder(self.edit_pre_tau_zero, self.edit_pre_tau_pole)
        dialog_control_edit.setTabOrder(self.edit_pre_tau_pole, self.checkBox_post_integrator)
        dialog_control_edit.setTabOrder(self.checkBox_post_integrator, self.edit_post_tau_i)
        dialog_control_edit.setTabOrder(self.edit_post_tau_i, self.edit_post_integrator_limit)
        dialog_control_edit.setTabOrder(self.edit_post_integrator_limit, self.checkBox_lead_back)
        dialog_control_edit.setTabOrder(self.checkBox_lead_back, self.edit_tau_zero_back)
        dialog_control_edit.setTabOrder(self.edit_tau_zero_back, self.edit_tau_pole_back)
        dialog_control_edit.setTabOrder(self.edit_tau_pole_back, self.checkBox_ff_use)
        dialog_control_edit.setTabOrder(self.checkBox_ff_use, self.edit_ff_kp)
        dialog_control_edit.setTabOrder(self.edit_ff_kp, self.checkBox_ff_pole_zero)
        dialog_control_edit.setTabOrder(self.checkBox_ff_pole_zero, self.edit_ff_tau_zero)
        dialog_control_edit.setTabOrder(self.edit_ff_tau_zero, self.edit_ff_tau_pole)
        dialog_control_edit.setTabOrder(self.edit_ff_tau_pole, self.buttonBox)

    def retranslateUi(self, dialog_control_edit):
        dialog_control_edit.setWindowTitle(_translate("dialog_control_edit", "Dialog", None))
        self.frame_kp.setToolTip(_translate("dialog_control_edit", "<html><head/><body><p>In not enabled, then no part of this controller is enabled.</p><p><br/></p><p>Proportional gain Kp</p><p>Kp may be zero (e.g. if feed forward is used only)</p></body></html>", None))
        self.ctrl_main_use.setText(_translate("dialog_control_edit", "Enable controller", None))
        self.label_kp.setText(_translate("dialog_control_edit", "Kp", None))
        self.label_ID.setText(_translate("dialog_control_edit", "wheel velocity", None))
        self.checkBox_pre_use.setText(_translate("dialog_control_edit", "Pre filter", None))
        self.label_pre_tau_zero.setText(_translate("dialog_control_edit", "Tau_zero", None))
        self.label_pre_tau_pole.setText(_translate("dialog_control_edit", "Tau_pole", None))
        self.label_ID_lead.setText(_translate("dialog_control_edit", "Controller parameters", None))
        self.checkBox_out_limit.setText(_translate("dialog_control_edit", "Output limit", None))
        self.label_out_limit.setText(_translate("dialog_control_edit", "max", None))
        self.checkBox_ff_use.setToolTip(_translate("dialog_control_edit", "<html><head/><body><p>Feed forward can be used even if Kp=0, and can then be used to feed the input directly to the output.</p></body></html>", None))
        self.checkBox_ff_use.setText(_translate("dialog_control_edit", "Feed forward", None))
        self.checkBox_ff_pole_zero.setText(_translate("dialog_control_edit", "Pole Zero", None))
        self.label_ff_tau_zero.setText(_translate("dialog_control_edit", "tau_zero", None))
        self.label_ff_tau_pole.setText(_translate("dialog_control_edit", "tau_pole", None))
        self.label_ff_kp.setText(_translate("dialog_control_edit", "Kf", None))
        self.frame_pole_zero_back.setToolTip(_translate("dialog_control_edit", "<html><head/><body><p>A first order filter with a pole and a zero.</p><p>The DC gain is 1 in any case (lead or lag configration.</p><p>Transfer function is:</p><p>G(s) = (tau_zero s + 1)/(tau_pole s + 1)</p></body></html>", None))
        self.checkBox_lead_back.setToolTip(_translate("dialog_control_edit", "<html><head/><body><p>Enable this part, to have a Lead-term (or lag) in the feedback branch.</p></body></html>", None))
        self.checkBox_lead_back.setText(_translate("dialog_control_edit", "Lead/lag in feed back", None))
        self.label_tau_zero_back.setText(_translate("dialog_control_edit", "Tau_zero", None))
        self.label_tau_pole_back.setText(_translate("dialog_control_edit", "Tau_pole", None))
        self.frame_post_integrator.setToolTip(_translate("dialog_control_edit", "<html><head/><body><p><span style=\" font-weight:600;\">Post integrator</span><br/>(advanced)</p><p>Post integrator can especially be used with balance control, where there may be need of either a clean integrator or an integrator with a zero at some (high) frequency.</p><p>If not including zero, then probably a Tau_i=1 should be used.<br/>The Tau_i is multiplied to the denominator of the function (including zero or not).</p></body></html>", None))
        self.checkBox_post_integrator.setToolTip(_translate("dialog_control_edit", "<html><head/><body><p>When <span style=\" font-style:italic;\">not</span> checked, then no post-integrator is added, and Kz=1 (in the controller overview block diagram)</p><p>When checked, then the selected post-integrator settings are enforced.</p></body></html>", None))
        self.checkBox_post_integrator.setText(_translate("dialog_control_edit", "post Integrator", None))
        self.checkBox_post_integrator_zero.setToolTip(_translate("dialog_control_edit", "<html><head/><body><p>If checked, then Kz (in the block overview diagram) is Kz=1, if not checked, then Kz=0.</p></body></html>", None))
        self.checkBox_post_integrator_zero.setText(_translate("dialog_control_edit", "including zero", None))
        self.label_post_tau_i.setText(_translate("dialog_control_edit", "Tau_i", None))
        self.edit_post_tau_i.setToolTip(_translate("dialog_control_edit", "<html><head/><body><p><span style=\" font-weight:600;\">Time constant for zero in integrator term</span></p><p>With zero</p><p>G = (tau_i s + 1)/(tau_i s)</p><p>Without zero</p><p>G = 1/(tau_i s)</p><p><br/></p></body></html>", None))
        self.label_post_limit.setText(_translate("dialog_control_edit", "Limit", None))
        self.edit_post_integrator_limit.setToolTip(_translate("dialog_control_edit", "<html><head/><body><p><span style=\" font-weight:600;\">Integrator limit</span></p><p>Limits the integrator value (symetrically around 0.0).</p><p>If no zero, then this effectively also limits the output.</p></body></html>", None))
        self.checkBox_integrator_use.setText(_translate("dialog_control_edit", "Integrator", None))
        self.label_tau_i.setText(_translate("dialog_control_edit", "Tau_i", None))
        self.label_integrator_limit.setText(_translate("dialog_control_edit", "Limit", None))
        self.frame_pole_zero_fwd.setToolTip(_translate("dialog_control_edit", "<html><head/><body><p>A first order filter with a pole and a zero.</p><p>The DC gain is 1 in any case (lead or lag configration.</p><p>Transfer function is:</p><p>G(s) = (tau_zero s + 1)/(tau_pole s + 1)</p><p><br/></p></body></html>", None))
        self.label_tau_pole_fwd.setText(_translate("dialog_control_edit", "Tau_pole", None))
        self.label_tau_zero_fwd.setText(_translate("dialog_control_edit", "Tau_zero", None))
        self.checkBox_lead_fwd.setText(_translate("dialog_control_edit", "Lead/lag in forward", None))
        self.pushButton_ctrlRetry.setToolTip(_translate("dialog_control_edit", "Request parameters from robot - discarding any unsaved changes.", None))
        self.pushButton_ctrlRetry.setText(_translate("dialog_control_edit", "Load from robot", None))
        self.pushButton_ctrlIniLoad.setToolTip(_translate("dialog_control_edit", "<html><head/><body><p>Load parameters from ini-file (regbot.ini)</p></body></html>", None))
        self.pushButton_ctrlIniLoad.setText(_translate("dialog_control_edit", "Load from ini", None))

